import type { Order } from "@/types/order-t";
import { OrderStatus } from "@/constants/order-status";

export const orders: Order[] = [
  {
    id: "sample-2301",
    number: "ORD-2301",
    clientId: "sample-1001",
    clientNumber: "1001",
    clientName: "Amal Carter",
    service: "Kitchen renovation",
    orderDate: "2026-04-22",
    deadline: "2026-06-14",
    price: 18450,
    status: OrderStatus.inProgress,
    materials: [
      { materialId: "MAT-101", name: "Porcelain tile", unit: "sq ft", quantity: 180, unitCost: 5.75 },
      { materialId: "MAT-102", name: "Cabinet paint", unit: "gal", quantity: 8, unitCost: 42 },
      { materialId: "MAT-103", name: "Quartz slab", unit: "slab", quantity: 2, unitCost: 680 },
    ],
  },
  {
    id: "sample-2302",
    number: "ORD-2302",
    clientId: "sample-1002",
    clientNumber: "1002",
    clientName: "Noah Bennett",
    service: "Bathroom remodel",
    orderDate: "2026-05-01",
    deadline: "2026-05-28",
    price: 9720,
    status: OrderStatus.materialsReady,
    materials: [
      { materialId: "MAT-101", name: "Porcelain tile", unit: "sq ft", quantity: 95, unitCost: 5.75 },
      { materialId: "MAT-104", name: "Waterproof membrane", unit: "roll", quantity: 3, unitCost: 88 },
      { materialId: "MAT-105", name: "Vanity fixture", unit: "unit", quantity: 1, unitCost: 420 },
    ],
  },
  {
    id: "sample-2303",
    number: "ORD-2303",
    clientId: "sample-1003",
    clientNumber: "1003",
    clientName: "Sara Haddad",
    service: "Full apartment refresh",
    orderDate: "2026-05-09",
    deadline: "2026-07-03",
    price: 24100,
    status: OrderStatus.planning,
    materials: [
      { materialId: "MAT-102", name: "Cabinet paint", unit: "gal", quantity: 12, unitCost: 42 },
      { materialId: "MAT-106", name: "Primer", unit: "gal", quantity: 10, unitCost: 24 },
      { materialId: "MAT-107", name: "Oak flooring", unit: "sq ft", quantity: 520, unitCost: 7.2 },
    ],
  },
  {
    id: "sample-2304",
    number: "ORD-2304",
    clientId: "sample-1004",
    clientNumber: "1004",
    clientName: "Leo Martinez",
    service: "Flooring replacement",
    orderDate: "2026-05-12",
    deadline: "2026-06-02",
    price: 6300,
    status: OrderStatus.scheduled,
    materials: [
      { materialId: "MAT-107", name: "Oak flooring", unit: "sq ft", quantity: 310, unitCost: 7.2 },
      { materialId: "MAT-108", name: "Floor adhesive", unit: "bucket", quantity: 6, unitCost: 36 },
    ],
  },
  {
    id: "sample-2305",
    number: "ORD-2305",
    clientId: "sample-1002",
    clientNumber: "1002",
    clientName: "Noah Bennett",
    service: "Entry repair",
    orderDate: "2026-04-10",
    deadline: "2026-05-10",
    price: 1850,
    status: OrderStatus.delayed,
    materials: [
      { materialId: "MAT-109", name: "Door casing", unit: "set", quantity: 1, unitCost: 145 },
      { materialId: "MAT-102", name: "Cabinet paint", unit: "gal", quantity: 2, unitCost: 42 },
    ],
  },
];
